ignore-patterns:
  - (^|/)\..+

strictness: veryhigh
autodetect: true
doc-warnings: true
test-warnings: true
member-warnings: false

# pylint:
#   disable:
#     - fixme
#     - bad-continuation
#     - invalid-name

#   options:
#     max-locals: 15
#     max-returns: 6
#     max-branches: 12
#     max-statements: 50
#     max-parents: 7
#     max-attributes: 7
#     min-public-methods: 2
#     max-public-methods: 20
#     max-module-lines: 1000
#     max-line-length: 79

# mccabe:
#   options:
#     max-complexity: 10

pep8:
  full: true
#   disable:
#     - E226
#     - E402
  options:
    max-line-length: 79
    single-line-if-stmt: n

# pyroma:
#   run: true
#   disable:
#     - PYR19
#     - PYR16

# pep257:
#   disable:
#     - D000
